name: AWS OIDC Connect Demo
on: 
    push
env:
    AWS_REGION: "ap-southeast-2"
permissions:
    id-token: write         # This is required for requesting the JWT 
    contents: read          # This is required for actions/checkout
jobs:
    DemoOIDC:
        runs-on: ubuntu-latest
        steps:
            - name: Git clone the repository
              uses: actions/checkout@v4

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                role-to-assume: arn:aws:iam::474008122042:role/github-oidc
                role-session-name: samplerolesession
                aws-region: ${{ env.AWS_REGION }}

            # - name: Print AWS SSM Parameter
            #   run: aws ssm get-parameter --name=hello_aws-gh-oidc --query Parameter.Value

            - name: Print assumed role
              run: aws sts get-caller-identity
              

